parameters:
  mavenImage: "maven:3.8.6-openjdk-11-slim"
  lintCommand: "make lint"
  testCommand: "make test"

steps:
  - script: |
      docker run --rm \
      -u $(id -u):$(id -g) \
      -v $(Build.SourcesDirectory):/workspace \
      -w /workspace \
      ${{ parameters.mavenImage }} \
      bash -c "apt-get update && apt-get install -y make && ${{ parameters.lintCommand }}"
    displayName: "Lint"

  - script: |
      docker run --rm \
      -u $(id -u):$(id -g) \
      -v $(Build.SourcesDirectory):/workspace \
      -w /workspace \
      ${{ parameters.mavenImage }} \
      bash -c "apt-get update && apt-get install -y make && ${{ parameters.testCommand }}"
    displayName: "Test"
