# Template (Azure Pipelines) - CI Java (steps)
#
# En la Práctica 5 se reutiliza este template desde el repo IaC.

parameters:
  mavenImage: "maven:3.8.6-openjdk-11"
  lintCommand: "make lint"
  testCommand: "make test"

steps:
  - script: |
      echo "TODO: ejecutar en contenedor: ${{ parameters.mavenImage }}"
      ${{ parameters.lintCommand }}
    displayName: "Lint"

  - script: |
      echo "TODO: ejecutar en contenedor: ${{ parameters.mavenImage }}"
      ${{ parameters.testCommand }}
    displayName: "Test"

    # Template (Azure Pipelines) - CI Java (steps)
