# Template (Azure Pipelines) - CI Python (steps)

parameters:
  pythonImage: "python:3.6-slim"
  requirementsFile: "requirements.txt"
  testCommand: "pytest -q"

steps:
  - script: |
      pip install --upgrade pip
      pip install -r ${{ parameters.requirementsFile }}
      ${{ parameters.testCommand }}
    displayName: "CI Python"
